/* Generated by scripts/build-gallery.js — do not edit the list by hand, alt texts may be edited. */
window.GALLERY_DATA = {
  "communications": [
    {
      "src": "img/communications/a_coeur_battant.jpeg",
      "alt": "Affiche « À cœur battant »"
    },
    {
      "src": "img/communications/accord_egalite.jpeg",
      "alt": "Affiche sur l'accord égalité professionnelle"
    },
    {
      "src": "img/communications/course_odyssea.jpeg",
      "alt": "Affiche de la course Odyssea"
    },
    {
      "src": "img/communications/duo_day.jpeg",
      "alt": "Affiche du Duo Day"
    },
    {
      "src": "img/communications/ensemble_avec_les_enterprises.jpeg",
      "alt": "Affiche « Ensemble avec les entreprises »"
    },
    {
      "src": "img/communications/invisible.jpeg",
      "alt": "Invisible"
    },
    {
      "src": "img/communications/journee_de_integration.jpeg",
      "alt": "Affiche de la journée d'intégration"
    },
    {
      "src": "img/communications/linkein_odyssea.jpeg",
      "alt": "Publication LinkedIn autour d'Odyssea"
    },
    {
      "src": "img/communications/momentRH.jpeg",
      "alt": "Affiche « Moment RH »"
    },
    {
      "src": "img/communications/politique_rh.jpeg",
      "alt": "Support de présentation de la politique RH"
    },
    {
      "src": "img/communications/prendre_une_pause.jpeg",
      "alt": "Affiche « Prendre une pause »"
    },
    {
      "src": "img/communications/retraite.jpeg",
      "alt": "Affiche de communication sur la retraite"
    },
    {
      "src": "img/communications/sexisme_ordinaire.jpeg",
      "alt": "Affiche de sensibilisation au sexisme ordinaire"
    },
    {
      "src": "img/communications/socks_1.png",
      "alt": "Socks 1"
    },
    {
      "src": "img/communications/socks_2.png",
      "alt": "Socks 2"
    }
  ],
  "photography": [
    {
      "src": "img/photography/animals/animals1.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 1"
    },
    {
      "src": "img/photography/animals/animals2.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 2"
    },
    {
      "src": "img/photography/animals/animals3.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 3"
    },
    {
      "src": "img/photography/animals/animals4.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 4"
    },
    {
      "src": "img/photography/animals/animals5.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 5"
    },
    {
      "src": "img/photography/animals/animals6.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 6"
    },
    {
      "src": "img/photography/animals/animals7.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 7"
    },
    {
      "src": "img/photography/animals/animals8.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 8"
    },
    {
      "src": "img/photography/animals/animals9.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 9"
    },
    {
      "src": "img/photography/animals/animals10.jpeg",
      "cat": "animals",
      "alt": "Photographie — Animaux 10"
    },
    {
      "src": "img/photography/events/events1.jpeg",
      "cat": "events",
      "alt": "Photographie — Événements 1"
    },
    {
      "src": "img/photography/events/events2.jpeg",
      "cat": "events",
      "alt": "Photographie — Événements 2"
    },
    {
      "src": "img/photography/events/events3.jpeg",
      "cat": "events",
      "alt": "Photographie — Événements 3"
    },
    {
      "src": "img/photography/events/events4.jpeg",
      "cat": "events",
      "alt": "Photographie — Événements 4"
    },
    {
      "src": "img/photography/landscape/landscape1.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 1"
    },
    {
      "src": "img/photography/landscape/landscape2.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 2"
    },
    {
      "src": "img/photography/landscape/landscape3.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 3"
    },
    {
      "src": "img/photography/landscape/landscape4.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 4"
    },
    {
      "src": "img/photography/landscape/landscape5.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 5"
    },
    {
      "src": "img/photography/landscape/landscape6.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 6"
    },
    {
      "src": "img/photography/landscape/landscape7.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 7"
    },
    {
      "src": "img/photography/landscape/landscape8.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 8"
    },
    {
      "src": "img/photography/landscape/landscape9.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 9"
    },
    {
      "src": "img/photography/landscape/landscape10.jpeg",
      "cat": "landscapes",
      "alt": "Photographie — Paysages 10"
    },
    {
      "src": "img/photography/marketing/marketing1.jpeg",
      "cat": "marketing",
      "alt": "Photographie — Marketing 1"
    },
    {
      "src": "img/photography/marketing/marketing2.jpeg",
      "cat": "marketing",
      "alt": "Photographie — Marketing 2"
    },
    {
      "src": "img/photography/nature/nature1.jpeg",
      "cat": "nature",
      "alt": "Photographie — Nature 1"
    },
    {
      "src": "img/photography/nature/nature2.jpeg",
      "cat": "nature",
      "alt": "Photographie — Nature 2"
    },
    {
      "src": "img/photography/nature/nature3.jpeg",
      "cat": "nature",
      "alt": "Photographie — Nature 3"
    },
    {
      "src": "img/photography/nature/nature4.jpeg",
      "cat": "nature",
      "alt": "Photographie — Nature 4"
    },
    {
      "src": "img/photography/nature/nature15.jpeg",
      "cat": "nature",
      "alt": "Photographie — Nature 15"
    },
    {
      "src": "img/photography/portrait/portrait1.jpeg",
      "cat": "portraits",
      "alt": "Photographie — Portraits 1"
    },
    {
      "src": "img/photography/portrait/portrait2.jpeg",
      "cat": "portraits",
      "alt": "Photographie — Portraits 2"
    },
    {
      "src": "img/photography/portrait/portrait3.jpeg",
      "cat": "portraits",
      "alt": "Photographie — Portraits 3"
    },
    {
      "src": "img/photography/portrait/portrait4.jpeg",
      "cat": "portraits",
      "alt": "Photographie — Portraits 4"
    },
    {
      "src": "img/photography/portrait/portrait5.jpeg",
      "cat": "portraits",
      "alt": "Photographie — Portraits 5"
    },
    {
      "src": "img/photography/portrait/portrait6.jpeg",
      "cat": "portraits",
      "alt": "Photographie — Portraits 6"
    },
    {
      "src": "img/photography/portrait/portrait7.jpeg",
      "cat": "portraits",
      "alt": "Photographie — Portraits 7"
    },
    {
      "src": "img/photography/portrait/portrait8.jpeg",
      "cat": "portraits",
      "alt": "Photographie — Portraits 8"
    },
    {
      "src": "img/photography/sports/sports1.jpeg",
      "cat": "sport",
      "alt": "Photographie — Sport 1"
    },
    {
      "src": "img/photography/sports/sports2.jpeg",
      "cat": "sport",
      "alt": "Photographie — Sport 2"
    },
    {
      "src": "img/photography/sports/sports3.jpeg",
      "cat": "sport",
      "alt": "Photographie — Sport 3"
    },
    {
      "src": "img/photography/sports/sports4.jpeg",
      "cat": "sport",
      "alt": "Photographie — Sport 4"
    },
    {
      "src": "img/photography/sports/sports5.jpeg",
      "cat": "sport",
      "alt": "Photographie — Sport 5"
    },
    {
      "src": "img/photography/street/street1.jpeg",
      "cat": "street",
      "alt": "Photographie — Street 1"
    },
    {
      "src": "img/photography/street/street2.jpeg",
      "cat": "street",
      "alt": "Photographie — Street 2"
    },
    {
      "src": "img/photography/street/street3.jpeg",
      "cat": "street",
      "alt": "Photographie — Street 3"
    },
    {
      "src": "img/photography/street/street4.jpeg",
      "cat": "street",
      "alt": "Photographie — Street 4"
    },
    {
      "src": "img/photography/street/street5.jpeg",
      "cat": "street",
      "alt": "Photographie — Street 5"
    },
    {
      "src": "img/photography/street/street6.jpeg",
      "cat": "street",
      "alt": "Photographie — Street 6"
    },
    {
      "src": "img/photography/street/street7.jpeg",
      "cat": "street",
      "alt": "Photographie — Street 7"
    },
    {
      "src": "img/photography/street/street8.jpeg",
      "cat": "street",
      "alt": "Photographie — Street 8"
    },
    {
      "src": "videos/beach.mp4",
      "cat": "videos",
      "type": "video",
      "alt": "Vidéo — Beach"
    },
    {
      "src": "videos/drone_1.mp4",
      "cat": "videos",
      "type": "video",
      "alt": "Vidéo — Drone 1"
    },
    {
      "src": "videos/reptile.mp4",
      "cat": "videos",
      "type": "video",
      "alt": "Vidéo — Reptile"
    },
    {
      "src": "videos/temple.mp4",
      "cat": "videos",
      "type": "video",
      "alt": "Vidéo — Temple"
    },
    {
      "src": "youtube:qC5DACA0N-Q",
      "cat": "videos",
      "type": "youtube",
      "id": "qC5DACA0N-Q",
      "alt": "Vidéo YouTube"
    }
  ]
};
