#!/usr/bin/env node
/*
 * Scans the image (and video) folders below (recursively) and writes js/gallery-data.js,
 * the lists of images the Communications carousel and the Photography
 * gallery display. In the "photography" gallery the first sub-folder of
 * each picture is its filter category (img/photography/<category>/...).
 *
 * Run it after adding, renaming or removing pictures:
 *     node scripts/build-gallery.js
 *
 * A static site cannot list a folder by itself, so this file is the bridge.
 * Alt texts already present in js/gallery-data.js are kept; new pictures
 * get one derived from their file name (edit it in that file if you like).
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const GALLERIES = {
  communications: { folder: "img/communications" },
  photography: {
    folder: "img/photography",
    categories: true,
    // every video in /videos is added to the gallery under the "videos" filter
    videosFolder: "videos",
    // folder name -> filter key used by the page (only where they differ)
    alias: { landscape: "landscapes", portrait: "portraits", sports: "sport" },
    // French label used to build alt texts
    labels: {
      animals: "Animaux", events: "Événements", landscapes: "Paysages", marketing: "Marketing",
      nature: "Nature", portraits: "Portraits", sport: "Sport", street: "Street", videos: "Vidéos"
    }
  }
};
const OUT = path.join(ROOT, "js", "gallery-data.js");
const EXT = /\.(jpe?g|png|webp|gif|avif)$/i;
const VIDEO_EXT = /\.(mp4|webm|m4v|mov)$/i;

function walk(dir, re = EXT) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return walk(p, re);
    return re.test(e.name) ? [p] : [];
  });
}

function humanize(file) {
  const base = path.basename(file, path.extname(file)).replace(/[_-]+/g, " ").replace(/([a-zà-ÿ])([A-Z])/g, "$1 $2").trim();
  return base.charAt(0).toUpperCase() + base.slice(1);
}

let previous = {};
try {
  const src = fs.readFileSync(OUT, "utf8");
  previous = JSON.parse(src.slice(src.indexOf("{"), src.lastIndexOf("}") + 1));
} catch (e) { /* first run */ }

const data = {};
for (const [key, cfg] of Object.entries(GALLERIES)) {
  const known = {};
  (previous[key] || []).forEach((i) => { known[i.src] = i.alt; });
  const base = path.join(ROOT, cfg.folder);
  data[key] = walk(base)
    .map((p) => path.relative(ROOT, p).split(path.sep).join("/"))
    .sort((a, b) => a.localeCompare(b, "fr", { numeric: true, sensitivity: "base" }))
    .map((src) => {
      const item = { src };
      let alt = humanize(src);
      if (cfg.categories) {
        const parts = path.relative(base, path.join(ROOT, src)).split(path.sep);
        if (parts.length > 1) {
          const folder = parts[0].toLowerCase();
          item.cat = (cfg.alias && cfg.alias[folder]) || folder;
          const n = (path.basename(src).match(/(\d+)\.[^.]+$/) || [])[1];
          alt = "Photographie — " + ((cfg.labels && cfg.labels[item.cat]) || humanize(parts[0])) + (n ? " " + n : "");
        }
      }
      item.alt = known[src] || alt;
      return item;
    });
  if (cfg.videosFolder) {
    walk(path.join(ROOT, cfg.videosFolder), VIDEO_EXT)
      .map((p) => path.relative(ROOT, p).split(path.sep).join("/"))
      .sort((a, b) => a.localeCompare(b, "fr", { numeric: true, sensitivity: "base" }))
      .forEach((src) => {
        data[key].push({ src, cat: "videos", type: "video", alt: known[src] || "Vidéo — " + humanize(src) });
      });
  }
  console.log(key + ": " + data[key].length + " image(s)");
}

fs.writeFileSync(OUT, "/* Generated by scripts/build-gallery.js — do not edit the list by hand, alt texts may be edited. */\nwindow.GALLERY_DATA = " + JSON.stringify(data, null, 2) + ";\n");
